database:
    ip: '127.0.0.1'
    database: 'admin'
    username: 'sql'
    password: 'abc123'
    port: 3306
    table: 'DynamicTags'
tagFormat: '&8<{TAG}&7{NAME}&8> &7{MESSAGE}'
defaultTag: ''
spaceAfterTag: true