name: DynamicTags
description: Dynamically assign tags via a command, stored in a MySQL database.
author: JoshK_
version: 1.0
main: eu.joshk.dynamictags.DynamicTags
commands:
    tag:
        description: Manage the tag system.